### ISSUE TITLE
panic on dangling symlinks

### ISSUE THREAD

**Issue by hrez** [EwenQuim/entropy#3]
If there is a symlink to non-existent file it panics:

to verify:

$ln -s nonExistantFile test

$entropy
No files provided, defaults to current folder.
panic: stat ./test: no such file or directory

I'd rather it skipped those.

**Comment by EwenQuim** [comment]
Well spotted.
I'll work on that

**Comment by benoist-folio** [comment]
Just hit this as well. It was actually quite useful as it ended up showing a number of broken symlinks in my code base, which I cleaned up, but it would be nice to ignore these broken links in the future.

**Comment by EwenQuim** [comment]
Fixed in f48b3cddf3ac87ec3927320538735802634a05d4
