### ISSUE TITLE
docker command is not working on linux amd64

### ISSUE THREAD

**Issue by nikhedonia** [EwenQuim/entropy#4]
great tool but you forgot to dockerise an amd64 build:

> docker run --rm -v $(pwd):/data ewenquim/entropy -top 20 -ext go,py,js /data

```
Unable to find image 'ewenquim/entropy:latest' locally
latest: Pulling from ewenquim/entropy
2dc97b63907c: Pull complete
72310de0f48e: Pull complete
4ca545ee6d5d: Pull complete
Digest: sha256:44a3c978bcf41ce31e40124747a1143a6918abab30481c306857b51cc0de5e53
Status: Downloaded newer image for ewenquim/entropy:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec ./main: exec format error
```

maybe we add the docker build to gha?

example gha: https://stackoverflow.com/a/77202719

**Comment by EwenQuim** [comment]
Thank you very much for the report!

Does it work now ? I fixed the docker image. 
I added a Makefile to make sure not to forget this step later.

**Comment by nikhedonia** [comment]
Yes it does! Thanks
